version: "3.9"
services:
    api:
        environment:
            NODE_ENV: production
        build:
            context: .
            dockerfile: Dockerfile.prod
        restart: always
        command: npm start